module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/HPnEiMHsiOd2djymlbsF3u',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://i.ibb.co/hFmR4Qvg/tourl-1768288598458.jpg',
    NEWSLETTER_JID: '120363421350428668@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '120363421350428668@newsletter',
    BOT_NAME: '【SᕼᗩGEE 】ᗰIᑎI ᗷOT',
    OWNER_NAME: 'ꪶ SᕼᗩGEE ꫂ ᴰ ᵀ ᶻ',
    OWNER_NUMBER: '94703403671',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> \`❝ Sʜᴀɢᴇᴇ 𝐌ᴅ 𝐌ɪɴɪ ♡🕊️ ❞\`',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb6A4FQJkK7AOqqfBM17',
};
